# Generated by Django 4.1.6 on 2023-03-20 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UVAClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("class_id", models.CharField(max_length=50)),
                ("subject", models.CharField(max_length=50)),
                ("class_description", models.TextField()),
                ("instructors", models.JSONField()),
                ("units", models.IntegerField()),
            ],
        ),
    ]
