# Generated by Django 4.1.6 on 2023-03-20 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transferguideApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("text", models.CharField(max_length=200)),
                ("date", models.DateTimeField(verbose_name="date published")),
            ],
        ),
    ]
