# Generated by Django 4.1.6 on 2023-04-01 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transferguideApp", "0002_news"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("course_subject", models.CharField(max_length=200)),
                ("credits", models.IntegerField()),
                ("transfer_institution", models.CharField(max_length=200)),
                ("url", models.CharField(max_length=200)),
            ],
        ),
    ]
