# Generated by Django 4.1.6 on 2023-04-16 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transferguideApp", "0003_courserequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="courserequest",
            name="status",
            field=models.CharField(default="Pending", max_length=200),
        ),
    ]
