# Generated by Django 4.1.6 on 2023-04-17 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transferguideApp', '0006_alter_courserequest_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courserequest',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
