# Generated by Django 4.1.6 on 2023-04-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transferguideApp', '0008_alter_courserequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='courserequest',
            name='course_equivalency',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='courserequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DENIED', 'Denied')], default='Pending', max_length=20),
        ),
    ]
