# Generated by Django 4.1.6 on 2023-04-17 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transferguideApp', '0009_courserequest_course_equivalency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courserequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DENIED', 'Denied')], default='PENDING', max_length=20),
        ),
    ]
