# Generated by Django 4.1.6 on 2023-05-03 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transferguideApp', '0010_alter_courserequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='img_src',
            field=models.CharField(default='/static/images/transfer.png', max_length=300),
        ),
    ]
