# Generated by Django 4.1.6 on 2023-05-03 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transferguideApp', '0011_news_img_src'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='img_src',
            field=models.CharField(default='images/transfer.png', max_length=300),
        ),
    ]
